"""stores table

Revision ID: 3fa03e3e87d8
Revises: d1e915b76225
Create Date: 2021-01-25 18:51:15.488732

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3fa03e3e87d8'
down_revision = 'd1e915b76225'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_store', sa.Column('lat', sa.Integer(), nullable=True))
    op.add_column('wine_store', sa.Column('lng', sa.Integer(), nullable=True))
    op.drop_column('wine_store', 'location')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_store', sa.Column('location', sa.VARCHAR(), nullable=True))
    op.drop_column('wine_store', 'lng')
    op.drop_column('wine_store', 'lat')
    # ### end Alembic commands ###
