"""users table

Revision ID: 83a86b5a3479
Revises: 69e6db397216
Create Date: 2021-01-29 15:36:18.298729

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83a86b5a3479'
down_revision = '69e6db397216'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_store', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('wine_store', sa.Column('vicinity', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wine_store', 'vicinity')
    op.drop_column('wine_store', 'address')
    # ### end Alembic commands ###
