"""stores table

Revision ID: 8ed50a7aad25
Revises: ca7d086cf33c
Create Date: 2021-01-29 15:36:46.878316

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ed50a7aad25'
down_revision = 'ca7d086cf33c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wine_store', sa.Column('address', sa.String(length=200), nullable=True))
    op.add_column('wine_store', sa.Column('vicinity', sa.String(length=180), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('wine_store', 'vicinity')
    op.drop_column('wine_store', 'address')
    # ### end Alembic commands ###
